language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2 CIBW_ENVIRONMENT="V=1"

script:
  - $PIP install cibuildwheel==0.9.4
  - cibuildwheel --output-dir wheelhouse
